const actionTypes = {
    FETCH_PRODUCTS : "FETCH_PRODUCTS",
    FETCH_PRODUCT : "FETCH_PRODUCT",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    ADJUST_QTY: "ADJUST_QTY",
    GET_USERS: "GET_USERS",
    REMOVE_SELECTED_USER: "REMOVE_SELECTED_USER",
    GET_ME: "GET_ME",
    SEARCH_BY_FILTER : "SEARCH_BY_FILTER",
    SEARCH_PRODUCT: "SEARCH_PRODUCT",
    POST_ORDER: "POST_ORDER",
    GET_ORDER_BY_EMAIl: "GET_ORDER_BY_EMAIl",
    GET_ALL_ORDER: "GET_ALL_ORDER",
    ADD_PRODUCT: "ADD_PRODUCT",
    UPDATE_PRODUCT: "UPDATE_PRODUCT",
    DELETE_PRODUCT: "DELETE_PRODUCT",
    ALL_USERS: "ALL_USERS"
};

export default actionTypes;