const actionTypes = {
    FETCH_PRODUCTS : "FETCH_PRODUCTS",
    FETCH_PRODUCT : "FETCH_PRODUCT",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    ADJUST_QTY: "ADJUST_QTY",
    GET_USERS: "GET_USERS",
    REMOVE_SELECTED_USER: "REMOVE_SELECTED_USER",
    GET_ME: "GET_ME",
    SEARCH_BY_FILTER : "SEARCH_BY_FILTER",
    POST_ORDER: "POST_ORDER",
    SEARCH_PRODUCT: "SEARCH_PRODUCT"
};

export default actionTypes;